CREATE TABLE Task (
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    statement VARCHAR(255) NOT NULL,
    `order` INT NOT NULL,
    type ENUM('OPEN_TEXT', 'MULTIPLE_CHOICE', 'SINGLE_CHOICE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    course_id BIGINT(20) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_task_course FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE
);


CREATE TABLE Task_option (
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    `option` VARCHAR(80) NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    task_id BIGINT(20) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_task_option_task FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE
);

